_target_: pytorch_lightning.callbacks.ModelCheckpoint

filename: last-epoch-{epoch}
auto_insert_metric_name: false
dirpath: ${path.working_dir}/checkpoints
every_n_epochs: 1
save_top_k: 1
save_last: false #to optimize
