_target_: pytorch_lightning.callbacks.ModelCheckpoint

filename: latest-epoch-{epoch}
auto_insert_metric_name: false
dirpath: ${callback.dirpath}/checkpoints/${run_id}/
monitor: step
mode: max
every_n_epochs: 50
save_top_k: -1
save_last: false
