_target_: temos.callback.VizCheckPoint

start_epoch: ???
filename: viz-epoch-{epoch}
auto_insert_metric_name: false
dirpath: ${path.working_dir}/checkpoints
monitor: step
mode: max
every_n_epochs: ???
save_top_k: -1
save_last: false
save_weights_only: true
